apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Deploy after Kafka cluster is ready (+1) and Flink operator is ready (-3)
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:imcbeth/homelab.git
    targetRevision: HEAD
    path: manifests/base/flink-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: flink-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
