apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:imcbeth/homelab.git
    path: manifests/base/ingress-nginx
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
