apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
spec:
  project: infrastructure
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 81.6.9
      helm:
        valueFiles:
          - $values/manifests/base/kube-prometheus-stack/values.yaml
        values: |
          admissionWebhooks:
            patch:
              annotations:
                argocd.argoproj.io/hook: PreSync
                argocd.argoproj.io/hook-delete-policy: HookSucceeded
          prometheusOperator:
            admissionWebhooks:
              createSecretJob:
                ttlSecondsAfterFinished: null # Or a value like 300
    - repoURL: git@github.com:imcbeth/homelab.git
      path: manifests/base/kube-prometheus-stack
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    # Grafana generates random admin password on each render if not using existingSecret
    - group: ""
      kind: Secret
      name: kube-prometheus-stack-grafana
      jqPathExpressions:
        - .data["admin-password"]
    - group: apps
      kind: Deployment
      name: kube-prometheus-stack-grafana
      jqPathExpressions:
        # Checksum annotation changes when secret changes
        - .spec.template.metadata.annotations["checksum/secret"]
