apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lifeonabike
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: lifeonabike
  source:
    repoURL: git@github.com:imcbeth/homelab.git
    targetRevision: HEAD
    path: manifests/base/lifeonabike
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
