apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-42"
spec:
  project: infrastructure
  sources:
    - repoURL: https://helm.linkerd.io/edge
      chart: linkerd-control-plane
      targetRevision: 2026.1.3
      helm:
        releaseName: linkerd-control-plane
        valueFiles:
          - $values/manifests/base/linkerd/values.yaml
    - repoURL: git@github.com:imcbeth/homelab.git
      path: manifests/base/linkerd
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
