apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-43"
spec:
  project: infrastructure
  sources:
    - repoURL: https://helm.linkerd.io/edge
      chart: linkerd-crds
      targetRevision: 2026.1.4
      helm:
        releaseName: linkerd-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
