apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-7"  # Deploy before Velero (-5) which depends on LocalStack S3
spec:
  source:
    path: manifests/base/localstack
    repoURL: git@github.com:imcbeth/homelab.git
    targetRevision: HEAD
  destination:
    namespace: localstack
    server: https://kubernetes.default.svc
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
