apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
spec:
  project: infrastructure
  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.18.3
      helm:
        releaseName: sealed-secrets
        valueFiles:
          - $values/manifests/base/sealed-secrets/values.yaml
    - repoURL: git@github.com:imcbeth/homelab.git
      path: manifests/base/sealed-secrets
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
