apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
spec:
  project: infrastructure
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: 1.24.4
      helm:
        valueFiles:
          - $values/manifests/base/tempo/values.yaml
    - repoURL: git@github.com:imcbeth/homelab.git
      path: manifests/base/tempo
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: tempo
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        # Prevent StatefulSet VCT changes from orphaning the iSCSI LUN on NAS
        - .spec.volumeClaimTemplates
        - .status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
