{
 "title": "Synology Dashboard",
 "tags": [ "Synology" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Server:", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modelName{job=\"snmp-docker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Serial",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "serialNumber{job=\"snmp-docker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{job=\"node-docker\", mode!=\"idle\"}[$__rate_interval])) * 100) / on(instance) sum by(instance) (irate(node_cpu_seconds_total{job=\"node-docker\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node-docker\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(node_load5{job=\"node-docker\"}) * 100) / count(count by(cpu) (node_cpu_seconds_total{job=\"node-docker\"}))"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(node_load15{job=\"node-docker\"}) * 100) / count(count by(cpu) (node_cpu_seconds_total{job=\"node-docker\"}))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 / node_memory_MemTotal_bytes{job=\"node-docker\"}) * (node_memory_MemTotal_bytes{job=\"node-docker\"} - (node_memory_MemFree_bytes{job=\"node-docker\"} + node_memory_Cached_bytes{job=\"node-docker\"} + node_memory_Buffers_bytes{job=\"node-docker\"} + node_memory_SReclaimable_bytes{job=\"node-docker\"}))"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"node-docker\"} - node_memory_SwapFree_bytes{job=\"node-docker\"}) / (node_memory_SwapTotal_bytes{job=\"node-docker\"} )) * 100"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node-docker\"} - node_boot_time_seconds{job=\"node-docker\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-docker\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"node-docker\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "upgradeAvailable{job=\"snmp-docker\"}"
    },
    {
     "expr": "version{job=\"snmp-docker\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "cpuFanStatus{job=\"snmp-docker\"}"
    },
    {
     "expr": "systemFanStatus{job=\"snmp-docker\"}"
    },
    {
     "expr": "systemStatus{job=\"snmp-docker\"}"
    },
    {
     "expr": "powerStatus{job=\"snmp-docker\"}"
    }
   ]
  },
  {
   "title": "Users / Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "serviceUsers{job=\"snmp-docker\"}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "Storage Usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-(100/raidTotalSize{job=\"snmp-docker\",raidName=\"Volume 1\"}*raidFreeSize{job=\"snmp-docker\",raidName=\"Volume 1\"})",
     "legendFormat": "Volume 1"
    },
    {
     "expr": "100-(100/raidTotalSize{job=\"snmp-docker\",raidName=\"Volume 2\"}*raidFreeSize{job=\"snmp-docker\",raidName=\"Volume 2\"})",
     "legendFormat": "Volume 2"
    },
    {
     "expr": "100-(100/raidTotalSize{job=\"snmp-docker\",raidName=\"Volume 3\"}*raidFreeSize{job=\"snmp-docker\",raidName=\"Volume 3\"})",
     "legendFormat": "Volume 3"
    },
    {
     "expr": "100-(100/raidTotalSize{job=\"snmp-docker\",raidName=\"Volume 4\"}*raidFreeSize{job=\"snmp-docker\",raidName=\"Volume 4\"})",
     "legendFormat": "Volume 4"
    },
    {
     "expr": "100-(100/raidTotalSize{job=\"snmp-docker\",raidName=\"Volume 5\"}*raidFreeSize{job=\"snmp-docker\",raidName=\"Volume 5\"})",
     "legendFormat": "Volume 5"
    },
    {
     "expr": "100-(100/raidTotalSize{job=\"snmp-docker\",raidName=\"Volume 6\"}*raidFreeSize{job=\"snmp-docker\",raidName=\"Volume 6\"})",
     "legendFormat": "Volume 5"
    }
   ]
  },
  {
   "title": "RAID Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "raidStatus{job=\"snmp-docker\", raidName=~\"Volume.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor-docker\", name=~\".+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Container Updates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "watchtower_containers_scanned{job=\"watchtower-docker\"}",
     "legendFormat": "Scanned"
    },
    {
     "expr": "watchtower_containers_failed{job=\"watchtower-docker\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "watchtower_containers_updated{job=\"watchtower-docker\"}",
     "legendFormat": "Updated"
    }
   ]
  },
  {
   "title": "Drives",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "diskTemperature{job=\"snmp-docker\"}"
    },
    {
     "expr": "diskType{job=\"snmp-docker\"}"
    },
    {
     "expr": "diskStatus{job=\"snmp-docker\"}"
    },
    {
     "expr": "diskModel{job=\"snmp-docker\"}"
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "ifPhysAddress{job=\"snmp-docker\", ifName=~\"eth.*|ovs_.*|bond.*\"}"
    },
    {
     "expr": "ifSpeed{job=\"snmp-docker\", ifName=~\"eth.*|ovs_.*|bond.*\"}"
    },
    {
     "expr": "ifOperStatus{job=\"snmp-docker\", ifName=~\"eth.*|ovs_.*|bond.*\"}"
    }
   ]
  },
  { "title": "CPU / RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"system\", job=\"node-docker\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node-docker\"}[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=~\".*irq\", job=\"node-docker\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node-docker\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode!='idle',mode!='system',mode!='iowait',mode!='irq',mode!='softirq', job=\"node-docker\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node-docker\"}[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"iowait\", job=\"node-docker\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node-docker\"}[$__rate_interval])))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"idle\", job=\"node-docker\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node-docker\"}[$__rate_interval])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"node-docker\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{job=\"node-docker\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{job=\"node-docker\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-docker\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"node-docker\"} - node_memory_MemFree_bytes{job=\"node-docker\"} - (node_memory_Cached_bytes{job=\"node-docker\"} + node_memory_Buffers_bytes{job=\"node-docker\"} + node_memory_SReclaimable_bytes{job=\"node-docker\"}))",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-docker\"} + node_memory_SReclaimable_bytes{job=\"node-docker\"}",
     "legendFormat": "RAM Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-docker\"}",
     "legendFormat": "RAM Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-docker\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "SWAP Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"node-docker\"}",
     "legendFormat": "SWAP Total"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"node-docker\"} - node_memory_SwapFree_bytes{job=\"node-docker\"})",
     "legendFormat": "SWAP Used"
    },
    {
     "expr": "node_memory_SwapFree_bytes{job=\"node-docker\"}",
     "legendFormat": "SWAP Free"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{job=\"cadvisor-docker\", name=~\".+\"}[1m])) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{job=\"cadvisor-docker\", name=~\".+\"}[1m])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_usage_bytes{job=\"cadvisor-docker\", name=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_spec_memory_limit_bytes{job=\"cadvisor-docker\", name=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=\"cadvisor-docker\", name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "HDD / SSD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Disk write io/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata1"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sda\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata1"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata2\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata2"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sdb\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata2"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata3\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata3"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sdc\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata3"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata4\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata4"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sdd\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata4"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata5\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata5"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sde\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata5"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata6\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata6"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sdf\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata6"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata7\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata7"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sdg\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata7"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata8\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata8"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sdh\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata8"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"nvme0n1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-nvme0"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"nvme1n1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-nvme1"
    }
   ]
  },
  {
   "title": "Disk write MB/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata1"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sda\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata1"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata2\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata2"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sdb\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata2"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata3\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata3"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sdc\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata3"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata4\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata4"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sdd\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata4"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata5\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata5"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sde\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata5"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata6\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata6"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sdf\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata6"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata7\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata7"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sdg\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata7"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata8\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata8"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sdh\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-sata8"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"nvme0n1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-nvme0"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"nvme1n1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "write-nvme1"
    }
   ]
  },
  {
   "title": "Disk read io/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata1"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sda\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata1"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata2\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata2"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sdb\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata2"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata3\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata3"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sdc\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata3"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata4\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata4"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sdd\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata4"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata5\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata5"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sde\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata5"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata6\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata6"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sdf\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata6"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata7\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata7"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sdg\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata7"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata8\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata8"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sdh\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata8"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"nvme0n1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-nvme0"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"nvme1n1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-nvme1"
    }
   ]
  },
  {
   "title": "Disk read MB/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata1"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sda\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata1"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata2\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata2"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sdb\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata2"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata3\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata3"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sdc\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata3"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata4\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata4"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sdd\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata4"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata5\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata5"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sde\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata5"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata6\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata6"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sdf\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata6"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata7\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata7"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sdg\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata7"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata8\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata8"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sdh\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-sata8"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"nvme0n1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-nvme0"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"nvme1n1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "read-nvme1"
    }
   ]
  },
  {
   "title": "Disk Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata1"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sda\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata1"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata2\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata2"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdb\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata2"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata3\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata3"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdc\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata3"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata4\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata4"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdd\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata4"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata5\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata5"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sde\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata5"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata6\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata6"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdf\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata6"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata7\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata7"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdg\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata7"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata8\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata8"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdh\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata8"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"nvme0n1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-nvme0"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"nvme1n1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-nvme1"
    }
   ]
  },
  {
   "title": "System Disk Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata1"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sda\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata1"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata2\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata2"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdb\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata2"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata3\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata3"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdc\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata3"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata4\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata4"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdd\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata4"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata5\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata5"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sde\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata5"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata6\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata6"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdf\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata6"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata7\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata7"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdg\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata7"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata8\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata8"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdh\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-sata8"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"nvme0n1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-nvme0"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"nvme1n1\", job=\"node-docker\"}[$__rate_interval])",
     "legendFormat": "util-nvme1"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Host - Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{job=\"snmp-docker\", ifName=~\"eth.*|ovs_.*|bond.*\"}[$__rate_interval])",
     "legendFormat": "{{label_name}}{{ifName}}"
    }
   ]
  },
  {
   "title": "Host - Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{job=\"snmp-docker\", ifName=~\"eth.*|ovs_.*|bond.*\"}[$__rate_interval])",
     "legendFormat": "{{label_name}}{{ifName}}"
    }
   ]
  },
  {
   "title": "Container - Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=\"cadvisor-docker\", name=~\".+\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container - Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"cadvisor-docker\", name=~\".+\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Node Exporter - Scrape Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_scrape_collector_duration_seconds{job=\"node-docker\"}",
     "legendFormat": "{{label_name}}{{collector}}"
    }
   ]
  },
  {
   "title": "SNMP Exporter - Scrape Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "snmp_scrape_duration_seconds{job=\"snmp-docker\"}",
     "legendFormat": "{{label_name}}{{job}}"
    }
   ]
  },
  {
   "title": "Status Exporter",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 103 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "cAdvisor Exporter - Scrape Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"cadvisor-docker\"}",
     "legendFormat": "{{label_name}}{{job}}"
    }
   ]
  }
 ]
}