---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-smtp-credentials
  namespace: default
spec:
  encryptedData:
    smtp_password: AgBlcFxrn4/NKZGA+TeTZAR3wY4APa2n2GfxSKw5hoavntnkV1MXJBD4+2aG/p3TrXkEufbMrBUOP36icCd3fLTGereTcZYeGdHs8ssLDA8kCxSfMH1DEK8oWdAqNVdivEDYZtWf3R4TxtxLdyT3QchIbJklmmUzyXWn1oT8Bc5bLQRj/gSk2d88b7g65TLT4HK1wa5/bWeuPX0e9f5dH+cKjGwtwj9iOED2yX/fwpk6yG0qxlzpoc2CtgqJxBwyW6eNYj7MnmV+wn/Sx87PrE471u3TV+Wcgxhl4XJ9j4/kDrymFJxoK2WdLr/of4D3f9UeUQ4J+UunJof8PsYDg2/VQBJlY3hkIB7rADyaytNRk3WO9pTyuy/R+eMY2cVOW8IIOnnybrgaENjQ7GeIxh0Mz1aeHh6FL6er7BMLDFLd4BySVKVplxB4J8tPZ6Z3ECU+/EK2qkvEcDMho2ESWfRbZhJT/Pc9DYhvYJkpnWbOMF0HilEQ6DWt7LJwyRahbF+9TuSJ8sy9MrKOOcHxlSGVnBURKMO2TeNG6Q7nqcGTq/6MHYkYXat5sT2lgqeQhNpvgQ6HS1Um2ohGJoJnhcpVt4DR98jlo9f+L72rE2Zq4v1kM59qXM4z9r+A5mDecXoBBZ9v6yT16SAaK/epLIJQ54WKjRSK2pGcvnfdPtcTqiRFUSbX2DTfr8CuQfGea5t7kbUOJp+DR8W8RQwI/Hjh9JS+
    smtp_username: AgAJ3wfY06WXYCm5FT2f8hSXTi3jr8kHenNCtOT0e3kOWaIOqdKVCr5ui0mSqFfW9FXQCLcS9xvekLMxhGQujZZ9L2fd4uz2DkBZb2Vq7NTKa2MQ1Sf/wSQymS1A4YU0sWCQd0NyYYU0Nhn19+zc8YBCQXRbbg/U3ub20+CirRCrT0EZYudZHLB1BPHwwmmaAjRZlEJFuCdyY3h5jOlNvRzBFnRCHKyD4R6cDW4gAcJe0Uj44y0IMauEUMR+aqDh581KCCCZNhYKbeBGDAspzQEi1zp6xkSprnx2XA7qcdNSvpQ7Xs36lWVJ8vt5uuj6vnff7cpi9A6R+kmQEKXkfefzhXSGqtW5RY59PynoDLk8v6KKnwcnHBsm86qyMzsv3js/3SZQuM2x56ekVJLeKQxpRL0kR2rKtlsy54E5e21G/ljDMO9ogOsa0XsJucNu0gU5LOqTqEnzd8wihHUnvICovVmI+qFMW1HedLJSaS4sVhT1JJH3Hvr403ijP7qzfxwig4i3dtYB8zP0pv6bzVA7vZeYXbtO5a1Xag3GC7pmZjehDHGD29y8B0QbL/Ki8oimp+seQzVbMMAzP8q6+ihlBrwCVrWq5IAtM2smnfwDSde3UqGxFFEnjAHhFc/2tfXklvMu0yHB3Im76sL85/jHeEkae987PJMMBhMpAd+z9qJIiv/cLPnbub1WX2c+m17V8YNTa/QNAeID8BfDkGc631sBO0M=
  template:
    metadata:
      name: alertmanager-smtp-credentials
      namespace: default
    type: Opaque
