---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-grafana
  namespace: default
spec:
  encryptedData:
    admin-password: AgBPEAQNLFt/CDGHP8h1Hmmv4x9YvzEEjlqKpXh9Sko5mhq9HX6lZ4jygbbjKhCI+brJYsY0NdX4FrFozVuoHL+5sLsF1c/YROv2Tj/3IAZ/kfB90RP+5YGYjml6VkUTHKI+IwbUoUgXH7X8zeJKsW5w+2LsqQwqsMJwbn53NegLevf+Noi+zeYpKdNUljPPxaLnTVQF/cQTitx0DjQdxXeRIfNTtJzYXq4WwK1o8offmGycbGNlF0ZuQ2BW9HamgKSbNDYpP20j9wxp1Zht5SHOWi9ndyfP/Sn50ubBsRzhme/c6sDVmUVaAaRfJjHIGAnIqZBKomrUk8kIMeDoD8bSCwBWVYpIRvF1eWIi72223PfeEpx3+X9XhYxfzyXpYWYG6gEMWDPKmW79H/+ZC4G6kt8W1RAF+uBNf9hATEJjojIy8xXZ7y1pmUW/Db0rIm2oGoGgMjMsO3vS4btzzs5MnRjLQIFar6uKNkYbEQONPynM+2tIhRBAYI1UXATPuAeqdTdGCaTr7vXMMkSGWCChSSAKBcYiVVm896qcrogUBrtK5e5LMexxYoh9ePRUQ/qRrOCGcM2VR0WQlBpNiIhJIXAbosSASjTVKp9IGqc614i+CNXvmMfXjw0vGNHHR9xlNuxl2N520wKupZ4vDg/pXkwh0n4sW/Um+ghBJ3JDGxD7b3AtDH7ZZx7US5vYxr+75ZProliUa93f
    admin-user: AgA2EoGsDqbZ4ezGL5XklGyAgNhEk5IzoOIJ1xslM26ahNZMBhAGWR2dS8dvqp7U6sK/cwxn8//ZRWLEVLmh6kHlnJkJxqxZLFQsQ+j6EQk5cYaEcfMNgK2OuuVNBhPtHluGgpWf4y+sMzm09iyI+/EsaWPv0X77tnsFeYQ7tgBy4ZTFZokSpnqR3jW3mSpXtBZ+p1fHg/4P+Glkm608WfHfomIrGAgL9qANCbPlOw3wfmwv1+WDvCBYO29vYKTJNC9uewN29kF/s64DuscqQRlxEyjmO89qIUzQRfue4O09FxVL4QAVNJBqj576kgAyPAPNzy3cy/byWFQstimXNvvBv+z+NeQexGUUGp8Cb3meeUC3rMLAgCS6DBsRveCiVUTdDyzMcTp0/Od0kfxhxWi6i4C0cEW4AFWmH2OEy08ELtEepLbE6t60pKpfXowPUAZN9gb88xdNq6YPCLkxK2+026GnKV3o0pjAxv+b4ZTEQiTatNHCliFUicP301vH0fptvWD+Aj79q7YuKJ8xiYyarGocZVRhROOBihSQbM3qk3fncfls0nkXP/q9Yo3ZnzvmXlniUSZYMt7Mhhmujom9SmVSy4v67oNI7WEtHhmKPQuezqObG1jCKMCu2T0PZDFJp1L8pcXqXjB9l04O1dO2fZQYL8m/9dGOrZJeG+CgWbVCmjcLUAdEfNl6U6FBeX9pZP/YQA==
  template:
    metadata:
      name: kube-prometheus-stack-grafana
      namespace: default
    type: Opaque
