apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Explicitly list resources to deploy (excluding values.yaml which is used by Helm)
resources:
  - blackbox-exporter-alerts.yaml
  - blackbox-exporter-configmap.yaml
  - blackbox-exporter-deployment.yaml
  - blackbox-exporter-service.yaml
  - grafana-secret.yaml
  - snmp-exporter-configmap.yaml
  - snmp-exporter-deployment.yaml
  - snmp-exporter-secret.yaml
  - snmp-exporter-service.yaml
  - velero-alerts.yaml
