apiVersion: v1
kind: ConfigMap
metadata:
  name: uni-poller-config
  namespace: unipoller
data:
  TZ: "America/Edmonton"
  UP_INFLUXDB_DISABLE: "true"
  UP_POLLER_DEBUG: "false"
  UP_PROMETHEUS_HTTP_LISTEN: "0.0.0.0:9130"
  UP_PROMETHEUS_NAMESPACE: "unpoller"
  UP_UNIFI_CONTROLLER_0_SAVE_ALARMS: "true"
  UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES: "true"
  UP_UNIFI_CONTROLLER_0_SAVE_DPI: "false"
  UP_UNIFI_CONTROLLER_0_SAVE_EVENTS: "true"
  UP_UNIFI_CONTROLLER_0_SAVE_IDS: "true"
  UP_UNIFI_CONTROLLER_0_SAVE_SITES: "true"
  UP_UNIFI_CONTROLLER_0_SITE: "n37-gw"
  UP_UNIFI_CONTROLLER_0_URL: "https://10.0.1.1"
  UP_UNIFI_CONTROLLER_0_USER: "imcbeth"
  UP_UNIFI_CONTROLLER_0_VERIFY_SSL: "false"
  UP_UNIFI_DYNAMIC: "false"
