apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - namespace.yaml
  - rbac.yaml
  - deployment-cloudflare.yaml
  - deployment-unifi.yaml
  - webhook-unifi-deployment.yaml
  - webhook-unifi-service.yaml
