apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - namespace.yaml
  - rbac.yaml
  - secret-cloudflare.yaml
  - secret-rfc2136.yaml
  - deployment-cloudflare.yaml
  - deployment-rfc2136.yaml
