---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-b2-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBp0ILqKzX+f2Uhr4P26RRRIwSnsAAROMroMl2JBI21icjLXceQUriJxh+opfaMHYqi0W3o0ua0J1VTjFUeeQU3zcwqKqW+EJ1Pm0zY47nJVOmzpg0UqdVwwH+nOMK9G477KR4U2ZBR4hz3z6/0Nj0NQJD3ur9kRe6uK7BKxLsmzICUZyIQCKSI/hK9q+sY79YheX7u7pJnFdGwkut5tKlmmCdyaaUnBlIYcfiI7A41W6MmrStThL4SusdS+8MJxWRK9AsQeBosEdYcZL2uLMNCFIBopAe/JBMyc3TRr78TEHrwdu9mmvveU6apCSOgvxV5qoId6kyVpzVtRCV1eYjoi0G0Ebjsh6IgjUBHpakBUAa/tHdQNO1R2ow2FY5gf3MOzhGsjCONDwtqf4k2zR8P2NAcXAF1/N+BXfDPMh3+QUgT8NSKRm81ft13AgpRBCykVyUjLFNcSgUTnnge6ei88/e0jZOJtVgXktwE4pNPV14lNi7oVYR7+j8GiXgrSP0++yzNiVWeyKAgNDjwhOUUs/3Dl5AVI5Rk7NZTFUH8wcfjOMXAKy8yz3UrEDNTq6tfIlZ+AdOSzwa0TpQlEp+zzW2FeVyKs1XPbtZWR0J3/JfGGdiNwuUmAbmjoEqwG58PA7fgXZrpSOymH4x6tsTSC5PAARYEv1wF8JEXT7x7VQxb4+aiePsPt5Zakvs+aYlXla6YRz57X/l1eyd77S5sWKcgP37zULdLnm/dy/sVrwJXOBuzaRjSW8oNvPEFqtTpd7iocEennaoaTLjtdHS2QisnynjLMwCwXXgRtnx5ILnb4S3qf9AJSUhn5hynGdAnLON7Qy3Bk+QKf9E=
  template:
    metadata:
      name: velero-b2-credentials
      namespace: velero
    type: Opaque
