{
 "title": "Synology Dashboard2",
 "tags": [
  "Synology",
  "DSM",
  "NAS"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Server:", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 1 },
   "targets": [
    { "expr": "modelName{}" },
    { "expr": "serialNumber{}" },
    { "expr": "memTotalReal{}" },
    { "expr": "count(diskIndex{})" },
    {
     "expr": "node_time_seconds{} - node_boot_time_seconds{}"
    },
    { "expr": "version{}" },
    { "expr": "upgradeAvailable{}" },
    { "expr": "temperature{}" }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(serviceUsers{}) by (serviceName)",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "System Checks",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "powerStatus{}" },
    { "expr": "systemStatus{}" },
    { "expr": "systemFanStatus{}" },
    { "expr": "cpuFanStatus{}" }
   ]
  },
  {
   "title": "UPS",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 5 },
   "targets": [
    { "expr": "upsInfoMfrName", "legendFormat": "__auto" },
    { "expr": "upsInfoModel", "legendFormat": "__auto" },
    { "expr": "upsInfoLoadValue", "legendFormat": "__auto" },
    { "expr": "upsInfoRealPowerNominal", "legendFormat": "__auto" },
    { "expr": "upsInfoStatus", "legendFormat": "__auto" },
    { "expr": "upsBatteryChargeValue", "legendFormat": "__auto" },
    { "expr": "upsBatteryRuntimeValue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAID Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "raidStatus{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "ifPhysAddress{ job=\"snmp-synology\", ifName=~\"eth.*|ovs_.*|bond.*\"}"
    },
    {
     "expr": "ifSpeed{ job=\"snmp-synology\", ifName=~\"eth.*|ovs_.*|bond.*\"}"
    },
    {
     "expr": "ifOperStatus{ job=\"snmp-synology\", ifName=~\"eth.*|ovs_.*|bond.*\"}"
    }
   ]
  },
  {
   "title": "CPU Activity",
   "type": "gauge",
   "description": "The percentage of CPU time spent processing user-level code, calculated over the last minute.",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by(instance) (irate(node_cpu_seconds_total{mode=\"system\", job=\"node-exporter\"}[1m0s])) +\n  sum by(instance) (irate(node_cpu_seconds_total{mode=\"user\", job=\"node-exporter\"}[1m0s]))\n) * 100 / on(instance) group_left sum by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\"}[1m0s]))",
     "legendFormat": "CPU Utilisation"
    }
   ]
  },
  {
   "title": "RAM Utilisation",
   "type": "gauge",
   "description": "Reserved memory, most recently pulled results.",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memTotalReal{} * 1024) by (job)",
     "legendFormat": "Size"
    },
    {
     "expr": "sum((memTotalReal{} - (memShared{} + memCached{} + memBuffer{} + memAvailReal{})) * 1024) by (job)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Volume 1 Storage",
   "type": "piechart",
   "description": "Current free and used space on Volume 1.",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raidFreeSize{ job=\"snmp-synology\",raidName=\"Volume 1\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "raidTotalSize{ job=\"snmp-synology\",raidName=\"Volume 1\"} - raidFreeSize{ job=\"snmp-synology\",raidName=\"Volume 1\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Volume 2 Storage",
   "type": "piechart",
   "description": "Current free and used space on Volume 2.",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raidFreeSize{ job=\"snmp-synology\",raidName=\"Volume 2\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "raidTotalSize{ job=\"snmp-synology\",raidName=\"Volume 2\"} - raidFreeSize{ job=\"snmp-synology\",raidName=\"Volume 2\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Exporter Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 12 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Drives",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "diskTemperature{ job=\"snmp-synology\"}"
    },
    {
     "expr": "diskType{ job=\"snmp-synology\"}"
    },
    {
     "expr": "diskStatus{ job=\"snmp-synology\"}"
    },
    {
     "expr": "diskModel{ job=\"snmp-synology\"}"
    }
   ]
  },
  {
   "title": "System Disk Activity",
   "type": "gauge",
   "description": "The percentage of time spent on disk IO, calculated over the last minute.",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=\"node-exporter\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Total Network Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(ifHCOutOctets{ job=\"snmp-synology\", ifName=~\"eth.*|ovs_.*|bond.*\"}[$__range]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(increase(ifHCInOctets{ job=\"snmp-synology\", ifName=~\"eth.*|ovs_.*|bond.*\"}[$__range]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Volume 3 Storage",
   "type": "piechart",
   "description": "Current free and used space on Volume 3.",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raidFreeSize{ job=\"snmp-synology\",raidName=\"Volume 3\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "raidTotalSize{ job=\"snmp-synology\",raidName=\"Volume 3\"} - raidFreeSize{ job=\"snmp-synology\",raidName=\"Volume 3\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Volume 4 Storage",
   "type": "piechart",
   "description": "Current free and used space on Volume 4.",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raidFreeSize{ job=\"snmp-synology\",raidName=\"Volume 4\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "raidTotalSize{ job=\"snmp-synology\",raidName=\"Volume 4\"} - raidFreeSize{ job=\"snmp-synology\",raidName=\"Volume 4\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU, RAM, Temperatures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Activity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"system\", job=\"node-exporter\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node-exporter\"}[$__rate_interval])))",
       "legendFormat": "System"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=~\".*irq\", job=\"node-exporter\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node-exporter\"}[$__rate_interval])))",
       "legendFormat": "IRQs"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode!='idle',mode!='system',mode!='iowait',mode!='irq',mode!='softirq', job=\"node-exporter\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node-exporter\"}[$__rate_interval])))",
       "legendFormat": "User"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"iowait\", job=\"node-exporter\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node-exporter\"}[$__rate_interval])))",
       "legendFormat": "I/O Wait"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node-exporter\"}[$__rate_interval])))",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "RAM Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(memTotalReal{} * 1024) by (job)",
       "legendFormat": "Size"
      },
      {
       "expr": "sum((memTotalReal{} - (memShared{} + memCached{} + memBuffer{} + memAvailReal{})) * 1024) by (job)",
       "legendFormat": "Reserved"
      },
      {
       "expr": "sum(memBuffer{} * 1024) by (job)",
       "legendFormat": "Buffer"
      },
      {
       "expr": "sum(memCached{} * 1024) by (job)",
       "legendFormat": "Cached"
      },
      {
       "expr": "sum(memShared{} * 1024) by (job)",
       "legendFormat": "Shared"
      },
      {
       "expr": "sum(memAvailReal{} * 1024) by (job)",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius{job=\"node-exporter\"}",
       "legendFormat": "CPU"
      },
      {
       "expr": "sum(diskTemperature{ job=\"snmp-synology\"}) by (diskID)",
       "legendFormat": "{{diskID}}"
      },
      { "expr": "temperature{}", "legendFormat": "System" }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Read (Total)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "increase(node_disk_read_bytes_total{}[$__range])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Data Write (Total)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "increase(node_disk_written_bytes_total{}[$__range])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Read (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{job=\"node-exporter\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Write (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_written_bytes_total{job=\"node-exporter\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Read (iops)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{job=\"node-exporter\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Write (iops)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_writes_completed_total{job=\"node-exporter\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{job=\"node-exporter\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Storage Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(raidTotalSize{} - raidFreeSize{}) by (raidName)",
       "legendFormat": "{{raidName}} Used"
      },
      {
       "expr": "sum(raidTotalSize{}) by (raidName)",
       "legendFormat": "{{raidName}} Size"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Network Traffic (Total)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ifHCInOctets{ job=\"snmp-synology\", ifName=~\"eth.*|ovs_.*|bond.*\"}[$__range])) by (ifName)",
       "legendFormat": "{{label_name}}{{ifName}}"
      }
     ]
    },
    {
     "title": "Sent Network Traffic (Total)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ifHCOutOctets{ job=\"snmp-synology\", ifName=~\"eth.*|ovs_.*|bond.*\"}[$__range])) by (ifName)",
       "legendFormat": "{{label_name}}{{ifName}}"
      }
     ]
    },
    {
     "title": "Received Network Traffic (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(ifHCInOctets{ job=\"snmp-synology\", ifName=~\"eth.*|ovs_.*|bond.*\"}[$__rate_interval])) by (ifName)",
       "legendFormat": "{{label_name}}{{ifName}}"
      }
     ]
    },
    {
     "title": "Sent Network Traffic (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(ifHCOutOctets{ job=\"snmp-synology\", ifName=~\"eth.*|ovs_.*|bond.*\"}[$__rate_interval])) by (ifName)",
       "legendFormat": "{{label_name}}{{ifName}}"
      }
     ]
    },
    {
     "title": "Active Sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(serviceUsers{}) by (serviceName)",
       "legendFormat": "{{serviceName}}"
      }
     ]
    },
    {
     "title": "Discards & Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(ifInDiscards{}[$__range])) by (ifName)",
       "legendFormat": "Discards In {{ifName}}"
      },
      {
       "expr": "sum(increase(ifInErrors{}[$__range])) by (ifName)",
       "legendFormat": "Errors In {{ifName}}"
      },
      {
       "expr": "sum(increase(ifOutDiscards{}[$__range])) by (ifName)",
       "legendFormat": "Discards Out {{ifName}}"
      },
      {
       "expr": "sum(increase(ifOutErrors{}[$__range])) by (ifName)",
       "legendFormat": "Errors Out {{ifName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Speedtest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "avg(speedtest_download_speed_Bps{})",
       "legendFormat": "Download"
      },
      {
       "expr": "avg(speedtest_upload_speed_Bps{})",
       "legendFormat": "Upload"
      }
     ]
    },
    {
     "title": "Download",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(max_over_time(speedtest_download_speed_Bps[1w:5m]))",
       "legendFormat": "Best"
      },
      {
       "expr": "min(min_over_time(speedtest_download_speed_Bps[1w:5m]))",
       "legendFormat": "Worst"
      },
      {
       "expr": "avg(avg_over_time(speedtest_download_speed_Bps[1w:5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Upload",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(max_over_time(speedtest_upload_speed_Bps[1w:5m]))",
       "legendFormat": "Best"
      },
      {
       "expr": "min(min_over_time(speedtest_upload_speed_Bps[1w:5m]))",
       "legendFormat": "Worst"
      },
      {
       "expr": "avg(avg_over_time(speedtest_upload_speed_Bps[1w:5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(min_over_time(speedtest_latency_seconds[1w:5m]))",
       "legendFormat": "Best"
      },
      {
       "expr": "max(max_over_time(speedtest_latency_seconds[1w:5m]))",
       "legendFormat": "Worst"
      },
      {
       "expr": "avg(avg_over_time(speedtest_latency_seconds[1w:5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(speedtest_latency_seconds{})",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(speedtest_scrape_duration_seconds{})",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "Test Results",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "targets": [
      { "expr": "speedtest_download_speed_Bps" },
      { "expr": "speedtest_upload_speed_Bps" },
      { "expr": "speedtest_latency_seconds", "legendFormat": "Latency" }
     ]
    }
   ]
  },
  {
   "title": "Docker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Network Traffic (Total)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(container_network_receive_bytes_total{name=~\".+\"}[$__range])) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sent Network Traffic (Total)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(container_network_transmit_bytes_total{name=~\".+\"}[$__range])) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Received Network Traffic (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Sent Network Traffic (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Container Activity Monitor",
     "type": "table",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval])) * 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "container_memory_usage_bytes{name=~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "container_spec_memory_limit_bytes{name=~\".+\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "(time() - container_start_time_seconds{name=~\".+\"})/86400",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval])) by (name) * 100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}