---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argo-workflows-b2-credentials
  namespace: argo-workflows
spec:
  encryptedData:
    access-key: AgCKGNy64uZKHMc1C/TFWvnNogy8QCC0tWUbzSojK8dqJDEP/tN1XaluetFzJ8Vv8LaoIWfY2DL0utyAn0tj3RnQ5gOcsBySaBWaPLCCQPlG/X71IvSIQK3MU5jScD1ceJuxDJIKe0TEmPq7TBSLJGD0xQp+rwfhOt4+30Siaw3OAHlNF2aKYpN01XEnlFmPKeMvLeotcjvc6m1GAYmlO8YIlNofi1Vf2K/F4dTTddU9N2KPGB8yeJKirNz5ReF+HNTEuNv99+eNBZgy8DKm42zzrIvWkck3SxlSEuRviT6LITIfP4GfW5CdHYJVQA9ruZdseK5K1YrqU364ZfCArBORyGK34Zkdt9xkfvU7+YnM3Yomb3X4YcBcNZ8jV4taWsDdzhIJ98iphspYQX+LFCDeq/Rh53tigYa24KE4vTJr0dVSbLZvi7KkAb94HUUi52F0WU/E8TJE4/ZwCKO424eeZgOHJKOmDAkkgz1J3XqEccGmm+ayfCbuskbNChP7D02If6oENqJqGvaCh8h5H9JWWGSKZDwBjGd5kYO/Si6sXpklH9LadNibOSLse6B7NBcxFfw8hWSxfecN2b1ekpOSZRBsGzJ45I3SolE52wf1Q1Ol634c1BjeRQza/xa6DUuSZhfNtLKai4I7xzoo3c0VYQLcFXCJxqsLSKJZ/81CAgW0rPonRt5YFt+Y2UsdvpUbJ/xJ2Qp66b+iwctz0DBDB4Gt0JX1ZonM
    secret-key: AgAi8Zdz3AlWKZB8lY+EUuNGL1Xiph2pF+n2kiWeAzDjCcqi0/evTy5ZrY+MNn9efTBTFwHe1/DEQULKMPz12GZG+b5Am8ymFL1pBDsD//gy/lIAHLM2Ph+0+OISBazidfjnlfLSwvsYQRld2SJB8M2XjpIw1bpoqQcB++N7hCccqmevII4JvAWzAdXK5F0VM8U3gBq/jgfFr47Jkf00NFmwbr/l39xpeCL/9f7igg6wHMcG2FUnQSloiu3Y+3m+F5k2wJ+XKbb2By89J9c8dJzcl0c6TLGjw1xkweYlMn6mbsaJhoGvD8rs6U3tkX7iSGNZ1tRARXci25BdJDeAo364g8xZIw4zD3Oi3GVdmvfP2Q4Kc9f6lPO+jJOk/mqTYepjIb/cG+3FlBloB2OvPXifyPBN4UBpcz9bKw3pfIEifX07XYNWZREet47bNu4lC78rcpvheN9/5sM0cDJ7MI5LO73XJa2/rvNOIYKbXEdxKRdJFJcgiRbgGi4nnWL9qX6+Lo0vI/0OGVKSob18pTLhenJiHjPX4CqgEkRDkABcjes5lgkw25QtI6t5I+/2CnT5I15cuFyRnbyt2GePgYamOE+kGKa2widICQOoP/3KyEdp1zWHVMZPIKlQ6c4HxYcVShnwtt8FGYvfWXPLJzjGwEJOZj3FMec5LhlILzjLsBjg9yBCHRh6BIbuP3noAkvAeFrDRw2200nFF1OzYQQWnev2jxH3OMjyFB25gF9e
  template:
    metadata:
      name: argo-workflows-b2-credentials
      namespace: argo-workflows
    type: Opaque
