---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argo-workflows-b2-credentials
  namespace: argo-workflows
spec:
  encryptedData:
    access-key: AgBVcxpHsyBy8bUw1GFr77QPaAJ5+plrKcclKnOrr6OZ6YuK0hr8I34MJpl6pgg3gZmeDAPfQzMiLDzPuP0m6SUmueLPWhxkOHIhgQSCp5CZ2eMiMsyL4z+KvB1UokiqiNygbbdw/lKnrPDsZpyQxKDhM/q8tJSq9Kz6nSYFpokZMlczY8CLuBdhAsD1ABZ9ksaxGWcgAbljYaDOL02RMupR8tcm/5aVc47juQU++wY361zN2o10SSZPJyorgey4CMvFw8+baSKdjPlz3GGjyLD7Vo29WkdcaITcECMf5WcRWgFtitFa0+BwcnUbUT88rp2QYADx2o+FWaz2/gEH6biX736ZHWuNveNDBy3F4w0fCyXZKlPzdPCKvwNzqlDSeE1myL35zhtaVllWQECxOrJegHa45r5i4T5iBBgqwEutAVaz81r6t5X1IXjBj3uEb+HrnRb0hNCL98jfa3O+jhD/eukpAvnaG4eV8zHp3nav+OWMsclmz2420/bepD/zDJakZCo/ydTXYOb3w8YPhDkaKf78sc8W7HQr+zgv3BY6S/GA/6/+GUyroQTEwmcHxGSw8rjJ9FAgD8H2s7b+/Jiw9nothjV08aY8xgkDwW324gzZOjWJDtThb4Lr0ySzKVKMxKOH6aYNGru0rVeYpfF2F8SiFGp8OFBwjsXPzyTSpphhFAiVzVPKHiB4Q5FZOlupENmASNs9m6w9GJ9emPSnfhJMOCzvt287
    secret-key: AgB2kzMVpKyyzM9/dG79qzgyMiRdjMKtCtSMUFTmQHzKx2eAfu0SGjdmI8/Rk8GHHd+PUCI6b85c58gkTSO4LEC894NfxN3UfGN6qa1FmVfxI7cPxI4Yo+3cD0mvqrW0oO6x/VHqohAhi3wUiJofLQtqHkp2zYiF9iy13N+eXhl66Ux9o3BQxPVi91dKqix9M9zffiSIked5qyYHyEqyW3dtbP8e/PDJ5NhOBN5YVBWiTWgvYu5HaE39rtCPdVWYjwzmvVtFLnGwuFeGqOqDhmMClNBsJQAaBw7fncPSkOOwRBTmhqzHTTT+RhyUNCoKX3OLD985B3NzeLuN4XEEWs54w6E1fVywKiqDrNsBEguZf5fpbaqtApEf3CqpkKLsj/b99nfc9xwxKS1mmLXinhXd7npFtk0AlEodM+u5nsPpbkPzaOIC2t3vT9eHYY6FepBm6+84wbdZKxMbTzd67qiuFkW2k/b3IPf8AXTCNjUht4J9o/ALejDQJ1rGMpFp2CpRWIKGWV6zosJQBJVJI6PyoI9jU0TUF5m45qvCsi9Jz7aeJtFDS1ZdWZWEqjTrfR/pv/AXHS5aqz9L2VjF+4QtrBl6efHpOVpfoS4ejAZAGfagEKWbw7A/gJIqKL/iK5Iw2sLYXZiNr8Aje8jXz6SFzPpE/R3cDS0uyQpTXlkKHfbfdUj90YCL8grCo5f1IeB2gDANvahMQboPM25Cmv+EFKbKg+7rPEKXChIQ5SqM
  template:
    metadata:
      name: argo-workflows-b2-credentials
      namespace: argo-workflows
    type: Opaque
