---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argo-workflows-b2-credentials
  namespace: argo-workflows
spec:
  encryptedData:
    access-key: AgAU2If1EB3qLqFCE54cWZqdqbNQMn2Lx6IiFrIQZ8pFAqub6YypoSxKXbzklQn3VA9g2wNyB7YOLhTiYQoTwj58uyMcPEd+KtdXNeWkesCd49B/MDDBiiljpSZ/wLQRmpuIaja2Pya9loedLRTgjko5U2goVNknhBBKRreisoZxJ3/cnG3i2KQqUQ8EROiBbNcRuLObJQc771b0OyfHjunJ7FHWcB3FEs10lQpS3zAiuWKze9ixooXgxhhZS3B6AValudig8kVCWeblRwXJ2RlPwcVQCL+x6pbV7uLhY3oY425NOXTWM/qCL09movgstIMI/ovpFo6EY/cGkVKdZUxAqGEb02lpE+n8RUWX+8aCDbmrZ2lxri9mgW/ou/rn8KHsanzuWp6M5l5Tyc30DrF0O9VjbrEiwBIfG8g40jq7djXCgBm+6cXsMyjaSsP4R+7FGxcLYTYPt9NojpvyH2srxmfVDNCJnUj3B1zKvGlfC5XEac86FwKkLOrhch1S+9CeggtBYMEZXxBMZT9bv9C0V79qdGb7WAdlknMZ2n4K+OPlbw1Hui7GQ+eXA7ouqQzi+pbbOb66wXqS3r4qJVB2PJt1E8GYgX40dCx3ljTHvmh3XqwdHXk3FQ5w6a17oL9Z+Ahb3GEa5YaOJ13n6rvJWIidZ6lgHhLbsoY+qQhoX7ACKEp1+oELohNOAhmNECFeseUdvxss0D7p/Ft0C2EAHMXaw0gNke05
    secret-key: AgCLY6jP7wgKI8cja1DO5OfnFs7zu5/SwXHM2j5GHDHyNOUJ77nzFLfPbs3YphTzRwHdngIlg9em0f4ZWlDdOSd3xrY3L52o5BNcWXYaoG29IRK3rdmoqXNHywoYUrMstg9eiyiyOcvsziNq/EHyBOMVdJCoLw7iCwxxOpPeSLlh/maIHR0rff3g2HSxj/y+7oeE319Mv2utfimF9GCTxOVQkTZ6rQ4/vAQMMOslaqM4JGN2sZZsMQ8BmHTcA9QAoj4QpJ/14SiEc/hklWcr2SPPndMiuz607FEunJhakmykihBA/SXtjiTVnQQXDGYL08SAZRUcaUPBpeWmcFdCqU0t8R0lDxj1ZLX9Oj4pEIzWNb5Ng34J/sKQ6ArUI9BO0n+gYrUl7IGsR6z1CRdQP8Lm9bCNMkTkGaenGkvljvieJLaqYSGwNd2QK5xQhaBjd+i4DteHpeQV/7VKQPw9xUpO+eAdPippVmUSzPEMaryjsrxXs5YUgnGyijZ1l3DdhNGXOmkjQxTPENTEWyR52Xaq58La91x770r6e7U9wQmEAx+vpzy2/LnOJzUsBa3O73iCYXpNnTXtjao8sC1IxK/afHmb+BR4cDzRLU53IL88icJDnqakkOvsfbisT2ktTEqET3DSobuFULjaeK/18VEE8M7wHBLsaAHMoV0xpUwnCOlrr2o4dGZAYMIXvM7H2qwhnbFxyu7yS6qa0cAtEcrQaWW7hrpqfXE4O8KuBCoy
  template:
    metadata:
      name: argo-workflows-b2-credentials
      namespace: argo-workflows
    type: Opaque
