---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lifeonabike-registry-creds
  namespace: argo-workflows
spec:
  encryptedData:
    .dockerconfigjson: AgATM4srHWa7Pq1KkjIWlDTWYXV8tAriYbj+7cm8ssBrexCMvQ1DCVSgzz76a4lm9wqbHB7S47KrZZe1MOg1hzEyWIf5uHHH7AHUm3OGu4AVcDyt5/7o4pa6K7BsiFBAf/YCazdHUGNhwqoxpwJvtoDc+blRuM8QAtyB60S3Ime5AX5K0kjibK/SmGkypulYj3pxoTe+U72ftirlflZsoSBZH0rj4CmCYvdOqaJ67C8IHPB0t9Id7YyJcliQ50tqnf5eTJXgwKfnoRZu2QmMcbGEbir3ZaFYc1jgvZj2K6b7L7eZneyWoLwxeTCnYvAUKeScgib1Ezs24BgmSbvXdORItl7vFWwzFW34pn20cUNlz/CWzZvMtFfGqqbcBdHTmRQQxigke/g979DGt7vY2g7eOhWm8dNxT/wLOld0qMkYj4lPqOt+bgRYKDYA7nYCDpwIXAwKvWaPyN5TOn87hfVIQRM73y+8WR5vZtz+3vfx0mVDdAxtptOGr9ZBQDSkppexb0WsHzmW/O3igZm8FzwE2dYuIi7mdWqEYXK/OsWvBwTkDUlAaw+EHJSC8i6HRPMZLfWB5EtY80HEG/8zRzhCum1i/XCrpyfU58ZOWPq8nirVNwjcuIav+gRDDDOW/YcwS1ZCa4Af76qQM020iAvB0kl4Fb+f/E1UGRxHGD5aW20m8u1C6AVrF5cwEzJTDnghdNxqrj7R6FzK2MaNA4Gdgv1XX+ctQQ9jZbN7rBhLymUnAL2FEWDq3/KCnNB5DlF8NTWci5ci0jPPMFJUsEUuf4POmZLqoncBxZ2Ju03Fs4N8zAXKDFJzK47KA4K8UKlMGLJKzpYN/cN42Peuu4m+jsqDhow49X0wbPzc2dnGlWxzIuxTOCaUb6fwkZJ46uzW
  template:
    metadata:
      name: lifeonabike-registry-creds
      namespace: argo-workflows
    type: kubernetes.io/dockerconfigjson
