---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zot-htpasswd
  namespace: zot
spec:
  encryptedData:
    htpasswd: AgB/wfWTY0LdtE+ptuL9NV8xua/2PhbRouokjMH2pBmK9oSW9m3pk15i8T4EEQL92r5t80o+RKo1NfyXMrQSmldT5FS3ngQy9fB9iDYpbi4fXXhn8w3v5G5sSmhM2rLk1ebin2BRmRlYdjypjisrIJUUamjtFzIJiRpAYEN4BhvALhoTpufMaKlDTXbR3n375qfrgOBj00fJFi8CW/u1VVyvEQ7avQYoktjgdc/ugy6pjFlXqfyPvGe/YAugvRi9dKDHbgMY/SiJUKvREEVTBcy3wzmLHNlJheHww0Jss00m2EdLaFjhnaxPcgSh2TDkG/5iv8i8UaaywwEETPAtw0WT8Ru1ZRj0MoSv7HQtVB6/lt5Z/1s3yAHJxNKqzi012SiKG5Vzo/s57g3YgxSnV0qB2I/fJg6nIBl317eoz4sq1QkzjU0k+DqgUUsV7DumnPtZD+vkKATxbBRyOI3ua1kJRSai02pHAiU02QNAIVppdk+IlR96CSmyrxtqubwSh6Tn5jTZO9HQfh5UXAjSZf/O1+iO1L+qAYnppCMSlcnvYud5L7gMOefJW+hWFffgSUUdUKQmEm3B56I6G7ddoOEknqxzEZ2mTvBDjU+f7Q0ecV81MxK4wQFyrmgq6TFwdI6GOHrK7MRxZCSrzCmJ2s+C15m5ROFdNUycKVeT7a/wUye430WC2PbjR8ezPR9r+UGZWAJJgzstKtZJ9udqnsJxTgnYbWN8M5QfkUKg/9NUYybXKCIxmAkYCca4fGTaaYQAVxgwqV69Rw2tixnqfVo1CA3U
  template:
    metadata:
      name: zot-htpasswd
      namespace: zot
