---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zot-htpasswd
  namespace: zot
spec:
  encryptedData:
    htpasswd: AgBG+3TpPuS6BbXYTQj7D9axr9dypKlnmTN0XIDjFoqhvzV15k8CBg+R8fVeYiI4ioZoSyiSY47FDjqavJVswwKDwms8KlDHLZzqTR2EKzOs7gdZIkdG9CCAPCCh7omKYPlD6Okp/Ir6eVg6yZcB8tgEDyh/DChcwHRStKkZvGouQaK0O3Do4FK60Hsy9H+wHNHQu4ouEsuHn+Plk2lXWN3k5Nr26LdCyqRLpynUhdNLEMEUZU1MAWMcGWNlduzvquhlJxAAJv3DfwiDr3/JPnSoWDrVpxd1RikoZaKWGWrZ2SdtHe5FZBXGv1axwuHxQuze5aATTjphilM63tUKL3Mabe43juJHcCEw6XiRq+I8WrBTNkZUOG+7hiyVXAU0fXbaXUaeyxOGsvohfOSMRTqVMJwKa6dQMu2PM+wKUT1wkPyzCTu0d/I51lo8TwoGIc4+bIRO001MAPQF4vqU5Bk3+sjcEMSskt6JCdJ3WsQn7f9N4TZTV/4MhrO5r+2DZf3m6jo30TiqCJ9aYegagwvVs7QnMAknzMLncRhEQhf6BmKfBkSfe9RKQ8scab/wSjqJDooDsHt8GHR5IiEOnu+Ggt4gZWIFEFM2O61P6UTaxfaLRyz7MdTZ3iV4r1dVUlnzbZWxdFEKp2DCWNFfiprltZ0WpMV4fxLwA6VsRFh1qjFBBLsyxXAC32B553tx1XwNR4tn9PzhLKPRaNsdQnfEG9Dxdyx+UDqruFEUQkqYJKrK8oYg6mvLQo7+yerqE9+Tvbp19gXhj7x/hqId
  template:
    metadata:
      name: zot-htpasswd
      namespace: zot
