---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zot-htpasswd
  namespace: zot
spec:
  encryptedData:
    htpasswd: AgA3xiEdem8z2YD32enSLvFHdHac5YjTsH4VolIA9x/58ej/jomTlEUsxbEem6Tle3nukCirOORaIKVS1fIYsQna06yHwEQG9Sh6rE28KCLvec4K0hFgmxT3wzT08Ac0w5oioPUdhZ618/EEy7JctJ0pXRhfzFJCm0irvZE5oTTg0gHm6QirJXqIQBS4puWket8qr3QJk/O/naBxkW86H5uaD+Tx3HoufoRd1k92LOMasP6W5hLSmcM+uXTevlgMzYv6d0J4uoGWT1ETuU5SkrPuvjweiAm/5dKDeFHPLFbyJ81YtHZ0yuzhMTMjMmK95k1RFn2XxRZZJb9rZYVPuGbwuCsqbStVI+1XDiXiXEaNaBU2r6pZWptuhp+boAN0FsGZgJToniSYWbNNty1KgDAA6XTuz4iKglUiAg66t7GNI9MvrtJt8fWIdOlKs93W9rczyO4LMTKX9N0kN/lQ9M67EpUNeZMsMahNKI/KQpOn/BMvW6TVDntFHObzL+jHlkICfUIe9TkVqsM0zh1OyKuh8dZ7rkkIDLjnO7aesoLNjMy9QFKB1xXnh21vFnmwXRmprlpMhUInXPpX2dH0yFCK0L75Jnfyg1KiJdhwIUbdr01OtDwfRVSibSwffsU0OsU/Yf8rasyYpLtIkeBcWvMcctT/zUt6Sy5lISogWJQJmY65GTiDLIL9/lVfVrYpNEENdE7K149ZWY9xuxGeES8PVznNcKsXBwycU3X3DOvJh+HX8ijImgLMe9sylDje1/IM+56tBSM4wxXNn20S5kS0ITE=
  template:
    metadata:
      name: zot-htpasswd
      namespace: zot
