apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Constraints (policy bindings in dryrun mode)
  # Deployed separately because these CRDs only exist after
  # Gatekeeper processes the ConstraintTemplates
  - require-resource-limits.yaml
  - allowed-repos.yaml
  - require-labels.yaml
  - block-nodeport.yaml
  - container-limits.yaml
