apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: snapshot-controller
  template:
    spec:
      containers:
        - name: snapshot-controller
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
