# localstack-manifests/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: localstack
spec:
  selector:
    matchLabels:
      app: localstack
  replicas: 1
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:4.12.0
          ports:
            - containerPort: 4566 # Default LocalStack port
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: SERVICES
              value: iam,s3,sns,sqs,lambda,dynamodb,ec2,elb # Enabled Services
            - name: DEBUG
              value: "1"
