apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localstack-data
  namespace: localstack
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-retain
  resources:
    requests:
      storage: 2Gi
