---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lifeonabike-registry-creds
  namespace: lifeonabike
spec:
  encryptedData:
    .dockerconfigjson: AgBUDd0UyWqjW+RdftWrzKls+he9gMFSWBW3dC2XH9zLz9st6W69C1QHAD/VZ8p2m1tVRaTvxqHZTVJTFG49fuSDry02WlmU91M9TKxfbehLLNXNZT8+7U5CDYwxUG2DCrcf6GnXSnCmJFNK80krt2a3FXWgfvQNEexcjefQkgZNRbNB2MsFFCHoh6cRVGH3aSoISF7nr6uytTEzR1YJAdwMrB81CYFrwNzG40pSEkqvEQtuHFXMcy+ui7g/3pGo9vMACvXHYU/mPXjux6ZKae62CM7UMMnOcB3SeZDFijUm5LNwPA6c8aV+t2obTk1HAAhTrsrK8tx8tIZgc98Wu/Fokw/eUwrf1rXG9t0vTMvQfY1JAG1PqjQJjsxB8ZJToCVtymNt0huI5vsdjgoxM6msJWUx7J0N4hUApdDUH7fneaHTjpuS+P2ogebZ8oObdPIf79dZfn4rGzI8jRyho31PqdwoH3ASWPunmxW0hXZ32dZiY7NnN1YZUUPGBnqpqmLdkQC9ZZAlpP5nff1X2YtDIK4P0V/Qld4hWh/w1AhyyC5iGs2lLRMVYqFCLoSg47Jgd3Jh0b8ZYefmeWFqVJbPRW0xk/zlNDYsN4Yhl9IUu7UUUBVnIFGMfzuEwxOoA3B5CYZtH7rgY5zzQAV8AdlDGIAXW81gy1n3K+eNZSgxcVHNr7ppncx9lnUuBXk6NRc2CxX03BKVbfp7csfOvfw0DmLqaRwf1QkJzRVm3NN8C6H6NL/wEwxN5yzauf1mCBbBr8gNfPdj4QB06aUoPsPEwG5I1tdHlHpLGogq3KRGgCCPgftF8TKqC/tdUWuvR8kJxwyDye/B8ew+h3p8TzZjQJ81FLYZ7XybKlcFYUmEeR4WRgSy6Q==
  template:
    metadata:
      name: lifeonabike-registry-creds
      namespace: lifeonabike
    type: kubernetes.io/dockerconfigjson
