---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: lifeonabike
spec:
  encryptedData:
    credentials.json: AgCYQiA05PSx9R9Qown+6JWQh/4ZQqF/r96XPTiY2TL+hAvzD2Gs58rGgyvKa3t7rfaxNN3UzXfP0/vbjvGSDpqIbHqOcD1qo+Z40mqoeKpvnhy0zsVhDkLubywB3DmxvPk7dBZADwo46jWqTxpudmWnhds9pbiAqjN8cZ0bjzrOtBLsfLAABaMBmYIs9PAkfEmVgEzTh7vMrdqMxSgM+mFNCP5dVKJPg0aR4ouW+vR+6XUBfx2Mx67hFYQcih+LpTFUO3LWfQ6P0F5VUxAFoEBzYs0E4sGQQWmtAzBwWpTiW9tP9DAPDij5AK9hV8F0P7CwgB2BZSQCnQJiYfq71EC8WYldWX0eoOlolKBfmwAwPBIOtfRaJ0OsoPN8JlZ70BpLr1fGVcdFDwVmRlDEKDb4t9/WbVLRfkn3YNm2SfDdXPeyH/q1E0Q8wdFtZmtWngD5fXVB8Ulyt6d8F6SECRyviYfocel8m87rQw2Bwk1YvK2CpRQVevDI3L/gCkXXIQzjlJ13olw4+YaF00t7B2f7UTG8o7RA0+U9VZRQKADgVQFOHf1awC+t/AqFKSALhVZmWliS3McK5eiLVmUC3PRLyn0cTaPChOr2uFyw/bMmVka7cniKOt8ts7C+68yhw8RaDvViRJvKAmKTYv3d8Nrgtfw3Z5IBsNQdi5T5uDNU80N5oqf6osf7Yqh1AJQRQ5BaNeZ13MG2HWUK+14xU1atBPGloD2iyD7RiUww2ear5fSWiqv/i6QeFw4q+JYwD0YNeMS+KmFzwo2e2ieKvZudB9MBYCeJjh/3XA8WMbELKsj0NvA4VEPnFv+Vo1lJ27tt1DOdfICWNnNDeYw1JJTitZVeiK5Q41hj+oZvEdwuKFWCW+yIfOhKk1mToT4BAYepIVxlggGvenD1xGAow0b+USiqtT1bFJnpBgkcybdw
  template:
    metadata:
      name: tunnel-credentials
      namespace: lifeonabike
    type: Opaque
